travis:
  secure:
    BINSTAR_TOKEN: sQ5/bvduhRB0zAQdHSdwROxnnU9cJ0YmXuElTarVkXEW5wJsjZWSGbA2X44npzwsTnDovnTNRpOj1l0/HGFLEn8qCURfInG7NXC6o9KSnstt6QFCkfobZAbwfErKY0uL41G/wCxdUoZVl77eD/n+VqO++yiKRvX/wR6hJ+nzgn/4Id7TJNmCfLzXq7YUvBtcRatu/ZBamdUg7Hp5lF+VreWnqAkwBxjIc1yf3h//tZRS20+cuhU0PTvfsxVkIvuPygxi6yyKdnEGsB7KkOq5zgrZf9DhrZ5gOqwyBqGCfy1upu7iryh6SGVbt1QM/ZPrMPXo0RUFacstMelc9VHCV5d8gJfYudddsK706DLn36p6WmGSAi40fd5p9w31RFncVJxsn7coEe0/e2Umy0X57zU5KTDmfCCwPt85xQoKzBruc9Xxjbz20JdJzy0KUrd6D9/jhcc/jNVe5EjCo5LYVDlcpgZ8foJ8w5992KDbBNOZ+AefJDyQAl01nbUT8CTo3btxhkfy94WAJwBIuTKJf4S3VRgSvYhvPHCv8mKsl7SfTch9ruCXgotjQwJCiWlLikvVTX3lcyecdTfKCeY66RrWw5IP14N55zqFC9F9TgJblK/rDvLKimpIRti+QNcfOCc9WgZD9WeFdkAJ3HeYW6Itqx1FNOSHFc+34jrEEw8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
